name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NugetApiKey}}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: |
        cd JsonConfigFlatter
        dotnet pack -c Release -o out
        
    - name: Push generated package to NuGet
      run: dotnet nuget push ./JsonConfigFlatter/out/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate --no-symbols true
      
